# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170305_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
